version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketchange
    volumes:
      - postgres-data:/var/lib/postgresql/data
  test-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketchangetest
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
  test-integration:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketchangeintegration
    volumes:
        - test-integration-postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketchange
    depends_on:
      - db

volumes:
  postgres-data:
  test-postgres-data:
  test-integration-postgres-data: