version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocketchange
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://username:password@db/pocketchange
    depends_on:
      - db

volumes:
  postgres-data: